title: Anmol Maini # your name (or website title) here
logo: "/images/IMG_7650.JPG" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  Class of 2021 @ MIT 
  <br><br>
  BS in Computer Science, Economics and Data Science
  <br> <br>
  <a href="/pdf/AnmolMainiResume4222020.pdf">Resume</a>
  <br> <br>
  <a href="https://www.linkedin.com/in/mainianmol/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
