title: Anmol Maini # your name (or website title) here
logo: "/images/IMG_7650.JPG" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  Rising Senior @ MIT 
  \n
  BS in Mathematical Economics
  <br> <br>
  <a href="https://www.linkedin.com/in/mainianmol/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
